version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: {{ prefix-name }}-{{ suffix-name }}-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"

volumes:
  postgres_volume:
